const CommonHead = () => {
  return ( 
    <>
      <meta charset="UTF-8"/>
      <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </>
   );
}
 
export default CommonHead;